# Site settings
title: Bryan Lawrence
email: b.n.lawrence@reading.ac.uk
description: > # this means to ignore newlines until "baseurl:"
  Intermittent rambings on climate, computing, or data science, what I'm
  up to, and what I'm thinking. Mostly professional, sometimes not.
disclaimer: >
  This is a personal site. Caveat Lector. Nothing written here reflects an official opinion of my employer or any funding agency. Laboris locatores analogum obsecro respice auferetur.
  (My daughter is learning Latin, unlike me, who never did!)
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username: bnlawrence
github_username:  bnlawrence
bitbucket_username: bnlawrence
include: ["_pages"]
address: >
    NCAS, Department of Meteorology
    University of Reading
# Build settings
markdown: kramdown

# Other options
permalink: /:categories/:year/:month/:title/
jobtitle: "Professor of Weather and Climate Computing"
author: Bryan Lawrence
#excerpt_separator:

# SEO stuff
google_author: "https://plus.google.com/u/0/110288225974212014913"
google_site_verification: "nfd8hkZSc3GmIivrLCudAdTq5m1kI0Ao7P1UyIt9z5Q"

plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll/tagging

tag_page_layout: tag_page
tag_page_dir: tags
tag_permalink_style: pretty

scholar:
    style: apa
    sort_by: year
    order: descending
    bibliography_template: bib
    repository: assets/papers
    bibtex-filters:
      - latex
      - markdown
