# Site settings
title: Bryan Lawrence
email: b.n.lawrence@reading.ac.uk
description: > # this means to ignore newlines until "baseurl:"
  Intermittent rambings on climate, computing, or data science, what I'm
  up to, and what I'm thinking. Mostly professional, sometimes not.
disclaimer: >
  This is a personal site. Caveat Lector. Nothing written here reflects an official opinion of my employer or any funding agency. Laboris locatores analogum obsecro respice auferetur.
  (My daughter is learning Latin, unlike me, who never did!)
baseurl: "" # the subpath of your site, e.g. /blog/
include: ["_pages"]
url: "https://www.bnlawrence.net/" # the base hostname & protocol for your site
twitter_username: bnlawrence
github_username:  bnlawrence
bitbucket_username: bnlawrence
address: >
    NCAS, Department of Meteorology
    University of Reading
# Build settings
markdown: kramdown

# Other options
permalink: /:categories/:year/:month/:title/
jobtitle: Professional Meeting Attendee
author: Bryan Lawrence
#excerpt_separator:

# SEO stuff

plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll/tagging
 # - jemoji

tag_page_layout: tag_page
tag_page_dir: tags
tag_permalink_style: pretty

scholar:
    style: apa
    sort_by: year
    order: descending
    bibliography_template: bib
    repository: assets/papers
    bibtex-filters:
      - latex
      - markdown
